### ISSUE TITLE
Typeahead bugs

### ISSUE THREAD

**Issue by snapjay** [engagepeople/podium-vue-components#10]
* When pressing enter to select an element in dropdown list; the list it does not close 
* It's possible to add the same item twice if data is retrieved from server
* Height of box changes when first item is added.  Should remain same as all inputs.
* Update Colors to match option D
![image](https://user-images.githubusercontent.com/60594/41726913-24d452aa-7541-11e8-8641-aa4891318cb1.png)

**Comment by vafl-brut** [comment]
https://github.com/engagepeople/podium-vue-components/pull/11
